[neo4j]
uri = "bolt://neo4j:7687"
user = "neo4j"
password = "strongpassword"

[openai]
server_url = "http://ollama:11434/v1"
api_key = "ollama"
server_url_generate = "http://ollama:11434/api/generate"
