services:
  streamlit:
    build:
      context: ./app
    ports:
      - '8501:8501'
    networks:
      - internal-net
    volumes:
      - ./app:/app
      - python-deps:/root/.cache/pip
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - fastapi  
      - neo4j

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/strongpassword  
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - internal-net
    restart: unless-stopped

  fastapi:
    build:
      context: ./fastapi
    ports:
      - '8000:8000'
    networks:
      - internal-net
    volumes:
      - ./fastapi:/app
      - python-deps:/root/.cache/pip
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - neo4j  

  ollama:
    image: ollama/ollama:latest
    ports:
      - '7869:11434'
    networks:
      - internal-net
    volumes:
      - ./ollama:/app/ollama
    environment:
      - OLLAMA_MODELS=/app/ollama/models
    restart: unless-stopped
    depends_on:
      - neo4j  

networks:
  internal-net:
    driver: bridge

volumes:
  python-deps: {}
  neo4j_data: {}
